language: node_js
cache: yarn
stages:
  - check
  - test
  - cov

node_js:
  - '12'
  - '14'

os:
  - linux
  - osx
  - windows

script: npx nyc -s yarn run test:node --bail
after_success: npx nyc report --reporter=text-lcov > coverage.lcov && npx codecov

jobs:
  include:
    - stage: check
      script:
        - yarn aegir dep-check
        - yarn run lint
        - yarn run build

    - stage: test
      name: chrome
      addons:
        chrome: stable
      script: npx aegir test -t browser -t webworker --node true --ts

    - stage: test
      name: firefox
      addons:
        firefox: latest
      script: npx aegir test -t browser -t webworker --ts --node true -- --browsers FirefoxHeadless

    - stage: test
      name: electron-main
      os: osx
      script:
        - npx aegir test -t electron-main --bail --ts

    - stage: test
      name: electron-renderer
      os: osx
      script:
        - npx aegir test -t electron-renderer --node true --bail --ts

notifications:
  email: false
