language: node_js
cache: yarn
stages:
  - check
  - test
  - cov

env:
  - YARN_GPG=no

node_js:
  - '12'
  - '14'

os:
  - linux
  - osx
  - windows

script: npx nyc -s yarn run test:node --bail
after_success:
  - npm install -g travis-deploy-once
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then travis-deploy-once "npx nyc report --reporter=text-lcov > coverage.lcov && npx codecov"; fi

jobs:
  include:
    - stage: check
      script:
        - yarn run check
        - yarn run lint
        - yarn run build

    - stage: test
      name: chrome
      addons:
        chrome: stable
      script: npx aegir test -t browser -t webworker

    - stage: test
      name: firefox
      addons:
        firefox: latest
      script: npx aegir test -t browser -t webworker -- --browsers FirefoxHeadless

    - stage: test
      name: electron-main
      os: osx
      script:
        - npx aegir test -t electron-main --bail

    - stage: test
      name: electron-renderer
      os: osx
      script:
        - npx aegir test -t electron-renderer --bail

notifications:
  email: false
