/**
 * Noise HFS (Hybrid Forward Secrecy) handshake state machine.
 *
 * Implements the XXhfs pattern:
 *   -> e, e1                    (Message A: DH ephemeral + KEM pubkey)
 *   <- e, ee, ekem1, s, es      (Message B: DH eph, DH(ee), KEM encap, static, DH(es))
 *   -> s, se                    (Message C: static, DH(se) — unchanged from XX)
 *
 * Protocol name: Noise_XXhfs_25519+XWing_ChaChaPoly_SHA256
 *
 * Security: handshake is secure if EITHER X25519 OR X-Wing (ML-KEM-768) is unbroken.
 * The classical DH operations (ee, es, se) provide current security; the KEM (ekem1)
 * provides quantum-safe forward secrecy against Store-Now-Decrypt-Later attacks.
 *
 * Token ordering in writeEkem1 / readEkem1:
 *   encryptAndHash(cipherText) FIRST — encrypted with the ee-derived key
 *   mixKey(sharedSecret) AFTER      — strengthens subsequent tokens (s, es, payload)
 *
 * References:
 *   - Noise HFS spec: https://github.com/noiseprotocol/noise_hfs_spec
 *   - PQNoise paper: ePrint 2022/539
 *   - X-Wing KEM: draft-connolly-cfrg-xwing-kem
 */

import { Uint8ArrayList } from 'uint8arraylist'
import { InvalidCryptoExchangeError } from './errors.js'
import { AbstractHandshakeState } from './protocol.js'
import type { HandshakeStateInit } from './protocol.js'
import type { IKem, KemKeyPair } from './kem.js'

export const NOISE_HFS_PROTOCOL_NAME = 'Noise_XXhfs_25519+XWing_ChaChaPoly_SHA256'

export interface HfsHandshakeStateInit extends HandshakeStateInit {
  /** KEM backend — provides generateKemKeyPair, encapsulate, decapsulate */
  kem: IKem
}

/**
 * XXhfs handshake state machine.
 *
 * Extends AbstractHandshakeState (which handles the three classical DH tokens:
 * ee, es, se) with two new KEM tokens: e1 and ekem1.
 *
 * The classical DH operations are UNCHANGED — this class only adds the parallel
 * KEM path. Both DH and KEM shared secrets are fed into MixKey(); the final
 * cipher keys depend on both.
 */
export class XXhfsHandshakeState extends AbstractHandshakeState {
  private readonly kem: IKem
  /** Local KEM ephemeral keypair — generated by initiator, stored for decapsulation */
  public e1?: KemKeyPair
  /** Remote KEM ephemeral public key — received from initiator, used for encapsulation */
  public re1?: Uint8Array

  constructor (init: HfsHandshakeStateInit) {
    super(init)
    this.kem = init.kem
  }

  // ─── KEM token write methods ────────────────────────────────────────────────

  /**
   * Write e1 token: generate KEM ephemeral keypair, transmit public key.
   *
   * Called by initiator in Message A. At this point there is no cipher key,
   * so encryptAndHash falls through to a plain mixHash — the pubkey is sent
   * unencrypted (1216 bytes on the wire, no AEAD tag).
   */
  protected writeE1 (): Uint8Array | Uint8ArrayList {
    if (this.e1 != null) {
      throw new Error('KEM ephemeral keypair already set')
    }
    this.e1 = this.kem.generateKemKeyPair()
    return this.ss.encryptAndHash(this.e1.publicKey)
  }

  /**
   * Write ekem1 token: encapsulate to remote e1 pubkey, transmit encrypted
   * ciphertext, then mix KEM shared secret into the chaining key.
   *
   * Called by responder in Message B, after writeEE() has established a cipher key.
   * Order is critical: encryptAndHash(cipherText) before mixKey(sharedSecret) so that
   * subsequent tokens (s, es, payload) are encrypted with the KEM-strengthened key.
   */
  protected writeEkem1 (): Uint8Array | Uint8ArrayList {
    if (this.re1 == null) {
      throw new Error('remote KEM ephemeral public key (re1) not set')
    }
    const { cipherText, sharedSecret } = this.kem.encapsulate(this.re1)
    const encrypted = this.ss.encryptAndHash(cipherText) // encrypt with ee-derived key
    this.ss.mixKey(sharedSecret)                          // then strengthen with KEM output
    return encrypted
  }

  // ─── KEM token read methods ─────────────────────────────────────────────────

  /**
   * Read e1 token: receive and store the remote KEM ephemeral public key.
   *
   * Called by responder in readMessageA. No cipher key exists yet, so
   * decryptAndHash is a no-op decrypt (plain mixHash). Returns bytes consumed.
   */
  protected readE1 (message: Uint8ArrayList, offset = 0): number {
    if (this.re1 != null) {
      throw new Error('remote KEM ephemeral public key already set')
    }
    const pkEncLen = this.kem.PUBKEY_LEN + (this.ss.cs.hasKey() ? 16 : 0)
    if (message.byteLength < offset + pkEncLen) {
      throw new Error('message too short for e1 token')
    }
    const raw = message.sublist(offset, offset + pkEncLen)
    const pk = this.ss.decryptAndHash(raw)
    this.re1 = pk.subarray()
    return pkEncLen
  }

  /**
   * Read ekem1 token: decrypt KEM ciphertext, decapsulate, mix KEM shared secret.
   *
   * Called by initiator in readMessageB. The ciphertext is AEAD-decrypted using
   * the ee-derived key, then decapsulated using the local e1 secret key. If the
   * ciphertext has been tampered with, AEAD decryption throws before decapsulation.
   * Even without tampering, wrong-key decapsulation (ML-KEM implicit rejection)
   * produces a divergent shared secret, causing all subsequent AEAD operations to fail.
   *
   * Returns bytes consumed from message.
   */
  protected readEkem1 (message: Uint8ArrayList, offset = 0): number {
    if (this.e1 == null) {
      throw new Error('KEM ephemeral keypair (e1) not set')
    }
    const ctEncLen = this.kem.CT_LEN + (this.ss.cs.hasKey() ? 16 : 0)
    if (message.byteLength < offset + ctEncLen) {
      throw new Error('message too short for ekem1 token')
    }
    const raw = message.sublist(offset, offset + ctEncLen)
    const cipherText = this.ss.decryptAndHash(raw)       // throws if AEAD tag invalid
    const sharedSecret = this.kem.decapsulate(cipherText.subarray(), this.e1.secretKey)
    this.ss.mixKey(sharedSecret)                          // same ordering as write side
    return ctEncLen
  }

  // ─── Message A: e, e1 ───────────────────────────────────────────────────────

  /**
   * Write Message A (initiator → responder):
   *   [32 bytes]   e.publicKey     (DH ephemeral, plaintext)
   *   [1216 bytes] e1.publicKey    (KEM ephemeral, plaintext — no cipher key yet)
   *   [payload]    encryptAndHash(payload)  (empty in standard handshake)
   *
   * Total (empty payload): 1248 bytes
   */
  writeMessageA (payload: Uint8Array | Uint8ArrayList): Uint8Array | Uint8ArrayList {
    const e = this.writeE()    // 32 bytes
    const e1 = this.writeE1() // 1216 bytes (plaintext — no AEAD tag)
    return new Uint8ArrayList(e, e1, this.ss.encryptAndHash(payload))
  }

  /**
   * Read Message A (responder side):
   *   Parses e (32 bytes) and e1 (1216 bytes), then decrypts payload.
   */
  readMessageA (message: Uint8ArrayList): Uint8Array | Uint8ArrayList {
    try {
      this.readE(message, 0)                                            // 32 bytes
      this.readE1(message, 32)                                          // 1216 bytes
      return this.ss.decryptAndHash(message.sublist(32 + this.kem.PUBKEY_LEN))
    } catch (e) {
      throw new InvalidCryptoExchangeError(`pq-handshake stage 0: ${(e as Error).message}`)
    }
  }

  // ─── Message B: e, ee, ekem1, s, es ────────────────────────────────────────

  /**
   * Write Message B (responder → initiator):
   *   [32 bytes]   e.publicKey          (DH ephemeral, plaintext)
   *   ee → MixKey(DH(e_R, e_I))        (classical forward secrecy)
   *   [1136 bytes] encryptAndHash(ct)   (KEM ciphertext + 16-byte AEAD tag)
   *   → MixKey(kem_output)             (quantum-safe forward secrecy)
   *   [48 bytes]   encryptAndHash(s)    (encrypted static pubkey + AEAD tag)
   *   es → MixKey(DH(e_I, s_R))        (classical authentication)
   *   [payload+16] encryptAndHash(payload)
   *
   * Total (empty payload): 32 + 1136 + 48 + 16 = 1232 bytes overhead
   */
  writeMessageB (payload: Uint8Array | Uint8ArrayList): Uint8Array | Uint8ArrayList {
    const e = this.writeE()           // 32 bytes
    this.writeEE()                    // MixKey(DH(ee)) — no bytes
    const ekem1 = this.writeEkem1()   // 1136 bytes (1120 ct + 16 AEAD)
    const encS = this.writeS()        // 48 bytes (32 static + 16 AEAD)
    this.writeES()                    // MixKey(DH(es)) — no bytes
    return new Uint8ArrayList(e, ekem1, encS, this.ss.encryptAndHash(payload))
  }

  /**
   * Read Message B (initiator side).
   */
  readMessageB (message: Uint8ArrayList): Uint8Array | Uint8ArrayList {
    try {
      this.readE(message, 0)                                    // 32 bytes
      this.readEE()                                             // DH(ee)
      const ekem1Consumed = this.readEkem1(message, 32)         // 1136 bytes
      const sConsumed = this.readS(message, 32 + ekem1Consumed) // 48 bytes
      this.readES()
      return this.ss.decryptAndHash(message.sublist(32 + ekem1Consumed + sConsumed))
    } catch (e) {
      throw new InvalidCryptoExchangeError(`pq-handshake stage 1: ${(e as Error).message}`)
    }
  }

  // ─── Message C: s, se (identical to XX) ────────────────────────────────────

  /**
   * Write Message C (initiator → responder):
   *   [48 bytes]   encryptAndHash(s)    (encrypted static pubkey + AEAD tag)
   *   se → MixKey(DH(s_I, e_R))        (classical authentication)
   *   [payload+16] encryptAndHash(payload)
   *
   * This message is unchanged from the classical XX pattern.
   */
  writeMessageC (payload: Uint8Array | Uint8ArrayList): Uint8Array | Uint8ArrayList {
    const encS = this.writeS()  // 48 bytes
    this.writeSE()              // MixKey(DH(se)) — no bytes
    return new Uint8ArrayList(encS, this.ss.encryptAndHash(payload))
  }

  /**
   * Read Message C (responder side).
   */
  readMessageC (message: Uint8ArrayList): Uint8Array | Uint8ArrayList {
    try {
      const sConsumed = this.readS(message, 0)  // 48 bytes
      this.readSE()
      return this.ss.decryptAndHash(message.sublist(sConsumed))
    } catch (e) {
      throw new InvalidCryptoExchangeError(`pq-handshake stage 2: ${(e as Error).message}`)
    }
  }
}
